services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 5173:5173
  server:
    image: server
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - 4000:4000
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database:/data
    ports:
     - 27017:27017



