services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 5173:5173
  server:
    image: server
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - 4000:4000
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@database:27017/
      ME_CONFIG_BASICAUTH: false